:PROPERTIES:
:ID:       5bf5434d-689c-49b6-b158-cf716ce14ee9
:ROAM_ALIASES: "HOME MANAGER"
:END:
#+title: Home Manager

-> [[id:b9e94588-3066-473f-a0ad-c0a266a46423][NIXOS]]

[[https://github.com/nix-community/home-manager][github page]]
[[https://nix-community.github.io/home-manager/][Home Manager Manual - nix-community]]
[[https://itsfoss.com/home-manager-nixos/][NixOS Series #5: How to set up home-manager on NixOS? - IT'S FOSS]]

[[https://www.magnusson.io/post/home-manager-review/][Review of home manager - Gunnar por Magnusson]]

* as a module

_note_: It will *require* sudo privileges to run *home-manager* as a NixOS module.

If using the _stable_ channel.
~# nix-channel --add https://github.com/nix-community/home-manager/archive/release-22.11.tar.gz home-manager~

If using the _unstable_ channel.
~# nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager~

*UPDATE THE CHANNELS*
~# nix-channel --update~

*EDITING CONFIGURATION.NIX*
Edit ~/etc/nixos/configuration.nix~ as root, and add the next
#+begin_src nix
{
  imports =
    [  # Include the results of the hardware scan.
      ./hardware-configuration.nix
      <home-manager/nixos>
    ];
#+end_src
Add this on the end of the file, before ~}~.
#+begin_src nix
...
  home-manager.users.<user> = { pkgs, ... }: {
  home.packages = [   ];
  };
}
#+end_src

*REBUILD THE SYSTEM*
Rebuild the config and switch into it:
~# nixos-rebuild switch~

_note_: If you're using _stable_, it will give you an error.
To solve this issue, you will have to add the next in your home manager block.
#+begin_src nix
...
  home-manager.users.<user> = { pkgs, ... }: {
  home.stateVersion = "22.11";
  home.packages = [   ];
  };
}
#+end_src

* as standalone
** install

If using the _stable_ channel.
~$ nix-channel --add https://github.com/nix-community/home-manager/archive/release-22.11.tar.gz home-manager~

If using the _unstable_ channel.
~$ nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager~


*UPDATE THE CHANNELS*
~# nix-channel --update~

And install the home manager:
~$ nix-shell '<home-manager>' -A install~

If you get an error, reboot the computer and run again

** adding packages

Everything now to edit will be on
~~/.config/home-manager/home.nix~

Add packages in
#+begin_src nix
home.packages = with pkgs; [

  # Add packages here
  neofetch
  slides

];
#+end_src

** commands

Read the news
~$ home-manager news~

[link to home-manager section]
https://nixos.wiki/wiki/Zsh

* tips
** checking whether package is installed with nix or home-manager

Check you have a package installed though home manager like this
~$ which btop~

*This is on Home Manager*
#+begin_src
/home/user/.nix-profile/bin/btop
#+end_src
*This is on regular Nix*
#+begin_src 
/run/current-system/sw/bin/btop
#+end_src
