:PROPERTIES:
:ID: 6b660401-e70d-43f3-a96e-9687eb1a6cf5
:END:
#+title: Terraform
#+options: num:nil author:nil timestamp:nil date:nil
#+setupfile: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* Resources

*Youtube*
> [[https://www.youtube.com/watch?v=cGPyH-PO8vg][Terraform has forever changed the way I deploy code - Dreams of Code]]
> [[https://youtu.be/tomUWcQ0P3k][Terraform in 100 Seconds - Fireship]]

** Deploying NixOS with Terraform
*** Github Description

What is a Terraform Module?

A Terraform Module refers to a self-contained package of Terraform configurations that are managed as a group. This repo contains a collection of Terraform Modules which can be composed together to create useful infrastructure patterns.
Terraform + Nix vs NixOps

NixOps is a great tool for personal deployments. It handles a lot of things like cloud resource creation, machine NixOS bootstrapping and deployment.

The difficulty is when the cloud resources are not supported by NixOps. It takes a lot of work to map all the cloud APIs. Compared to NixOps, Terraform has become an industry standard and has thousands of people contributing new cloud API mapping all the time.

Another issue is when sharing the configuration as code with multiple developers. Both NixOps and Terraform maintain a state file of "known applied" configuration. Unlike NixOps, Terraform provides facilities to sync and lock the state file so it's available by other users.

The approach here is to use Terraform to create all the cloud resources. By using the google_image_nixos_custom module it's possible to pre-build images in auto-scaling scenarios. Or use a push model similar to NixOps with the generic deploy_nixos module.

So overall Terraform + Nix is more flexible and scales better. But it's also more cumbersome to use as it requires to learn two languages instead of one and the integration between both is also a bit clunky.
Terraform Modules

The list of modules provided by this project:

    deploy_nixos - deploy NixOS onto running NixOS machines
    google_image_nixos - setup an official GCE image into a Google Cloud Project.
    google_image_nixos_custom - build and deploy a custom GCE image into a Google Cloud Project

Using these modules from your terraform configuration

Terraform supports importing modules directly from a GitHub repository.

For example, to use the deploy_nixos module:

module "deploy_nixos" {
  source = "github.com/tweag/terraform-nixos//deploy_nixos?ref=ced68729b6a0382dda02401c8f663c9b29c29368"

  … module-specific fields …
}

Beware the double //, which separates the github repository url from the subdirectory that contains the module. ?ref= specifies a specific git ref of the repository, in this case the commit ced687….

*** Tutorial

Way to handle resources, similar idea as Chef, Puppet and Ansible.
Only applied to cloud resources.

You have a binary like an engine, and resources.

Resources provided by a provider, a provider is a plugin mapped to something like Google Cloud.

Each of these resources map to a VM, Firewall Config, Disk Image

You describe using a *Terraform* language, using *HCL*.
Run 

Terraform to manage
- Linux NixOS
- Windows
* Tutorials
** Terraform Course - Automate your AWS cloud infrastructure

> [[https://youtu.be/SLB_c_ayRMo][Terraform Course - Automate your AWS cloud infrastructure - freeCodeCamp.org]] (youtube video)

> Create a AWS account.
> Download Terraform executable or install in Linux.
> [Windows] Copy the path of the executable, and add it to the Environment Variables, add to PATH. So you can access from terminal.

-----


* Usage
* Other
** OpenTofu
:PROPERTIES:
:ID:       4ad798b9-b593-4326-adcb-b7c165b86a6d
:END:

+ [[https://github.com/opentofu/opentofu][OpenTofu - github page]]
+ [[https://opentofu.org/docs/intro/core-workflow][The Core OpenTofu Workflow - OpenTofu]]

Download the binary from releases, then add the binary to your PATH.

** terranix
:PROPERTIES:
:ID:       72f64061-a082-4826-9a54-00084a068577
:END:

+ [[https://terranix.org/][Main page - terranix.org]]
