rootUrl = 'https://asynthe.github.io'
language = 'en-US'
title = 'asynthes blog'
author = 'nixos'

# Code blocks highlighting
[highlighter]
enable = false
# engine = 'prism' # Can be 'prism' or 'hljs'. Defaults to 'prism'

# RSS feed
[rss]
enable = true
description = 'Latest posts'
ttl = 60
image = '/assets/favicon.png'