#+title: Docker
#+options: num:nil author:nil timestamp:nil date:nil
#+setupfile: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

Written in Go.

* Resources

https://nixos.wiki/wiki/Docker

*Book*
> Docker: Up & Running

** Docker Tutorial for Beginners - Ben Awad

> [[https://youtu.be/0N3n56KsC28][Docker Tutorial for Beginners - Ben Awad]] (youtube video)

Create a file called ~dockerfile~
We are going to build a image, this will be called a *container*

- [[https://hub.docker.com][dockerhub]]

FROM <name of image>:<version> (check on dockerhub)
COPY <source of files> <where to store the container>
RUN <command that installs dependencies, ex: npm install>

*DOCKERFILE*
#+begin_src dockerfile
FROM node:latest

COPY . .

RUN npm install

CMD node src/index.js
#+end_src

Creating the container.
~$ docker build -t <name>/<container-name>:<version>~
_example_: ~$ docker build -t benawad/node-example:1 .~

_note_: Whenever chaning the code you will have to rebuild the image, rebuild it with same command as before, but specify a new version
_example_: ~$ docker build -t benawad/node-example:2 .~

Running the image
~$ docker run -p <port to open>:<port specified on app> <name>/<container -name>:<version>~
_example_: ~$ docker run -p 8001:3001 benawad/node-example:1~
_note_: It will lock your terminal, specify ~-d~ flag to detach into background.

See all the running containers and their ID's
~$ docker container ls~

Stop a container
~$ docker container stop <container-id>~

To check logs, add a console output to your code, and do the next
~$ docker container logs <container-id>~

* Usage

> [[https://hub.docker.com][dockerhub]]

When it's running -> *container*
When it's being built / before running -> *image*

Build this image.
~# docker build . -t my_first_image~

Check the images on your system.
~# docker images~

Get the image for debian latest.
~# docker pull debian:latest~

~# docker run -dit --name myContainer <image name>~

~-d~ -> Run on background independently.
~-i~ -> Interactive.
~-t~ -> Terminal.

~--name~ -> my Container
~<image name>~

See running containers.
~# docker ps~

Connect to container.
~# docker exec -it myContainer bash~

You will change now to the terminal in the container.
-> ~root@<container id>~

---
Ubuntu

Installing packages on this container.
~:/# apt update~
~:/# apt install iputils-ping~
~:/# ping <host ip>~

* Commands
** port
** build

Build an image from a Dockerfile.
~# docker build -t . <name>:<tag> <dir/of/dockerfile>~
_example_: ~# docker build -t my_first_image:v2 .~

** exec

Execute a command in a running container.
~# docker exec <container name/ID>~
_example_: ~# docker exec -it myContainer bash~

Flags
~-i~ / ~--interactive~ -> Keep STDIN open.
~-t~ / ~--tty~ -> Allocate a pseudo-TTY.

** images

List the images built from Dockerfiles.

** ps

Show currently running containers.
~# docker ps~

~-a~ / ~--all~ -> List all containers on the host.
~-q~ / ~--quiet~ -> Only show container ID's.

** rm

Remove a container.
~# docker rm <container/name/or/id>~
_note_: It won't work for running containers, you will have to stop them. Or run the ~--force~ flag.

Remove containers even running ones.
~# docker rm <container/name/or/id> --force~

Remove all containers.
~# docker rm $(docker ps -a -q)~
_note_: If root is needed then ~$ sudo docker rm $(sudo docker ps -a -q)~

** rmi

Check the images on the system.
~# docker images~

Delete an image.
~# docker rmi <image name>~

Delete all images.
~# docker rmi $(docker images -q)~
_note_: If root is needed then ~$ sudo docker rmi $(sudo docker images -q)~

** run

Create and run a container from an image.
~# docker run [options] <name of image>~
_example_: ~# docker run -dit myContainer myimage~

Create and run a container with a folder mounted to the */var/www/html* folder and attached to port 80.
~# docker run -dit -p 80:80 -v /home/user/webfiles:/var/www/html --name myWebServer webserver~
_note_: Adding a ~:ro~ at the end of the mount will make the files be read-only.

Flags
~-d~ / ~--detach~ -> Run container in background.
~-i~ / ~--interactive~ -> Keep STDIN open.
~-t~ / ~--tty~ -> Allocate a pseudo-TTY.
~-p~ / ~--publish~ ~<number>~ -> Publish a container port to the host.
~-v~ / ~--volume <path>~ -> Mount a volume or folder to the container.
~--name <string>~ -> Give a name to the container.

** stop

Stops a running container.
~# docker stop <container/name/or/id>~

** logs

Get logs of a specific container.
~# docker logs <container/name/or/id>~

** volume

~# docker volume ls -q~
~# docker volume rm $(docker volume ls -q)~
-> ~$ sudo docker volume rm $(sudo docker volume ls -q)~

* Tips
** Stopping the Docker daemon

> [[https://stackoverflow.com/questions/42365336/how-to-stop-docker-under-linux][How to stop docker under Linux - StackOverflow]]

Stop the docker container with.
~# systemctl stop docker~

Stop the socket too if required.
~# systemctl stop docker.socket~

** iptables rules on Docker

iptables on Docker

~# docker run -dit -p 80:80 --cap-add=NET_ADMIN --name myContainer my_image~
~# docker exec -it myContainer bash~
~# apt install iptables -y~

** Nix

> [[https://thewagner.net/blog/2021/02/25/building-container-images-with-nix/][Building container images with Nix]]

...

* Docker Compose
:PROPERTIES:
:ID:       5cf351a5-3ffa-4580-bb9c-3f330ce63231
:ROAM_ALIASES: Docker-Compose
:END:

Will read the ~docker-compose.yml~ inside the folder.

Build the images and run the container(s).
~# docker compose up -d~

Tear down the compose.
~# docker compose down~

* Podman
:PROPERTIES:
:ID:       379F85BD-9E2A-4DB5-AAEB-389C32C40E98
:END:

+ [[https://podman.io/][main page]]

While most of the commands can be run as user, there will be sometimes where you will need to execute as *root*.

_example_: Run the ~nginx~ container and expose port 80
~$ podman run -p 80:80 -d nginx~
This will fail as all ports below <=1024 are privileged ports, so we need to be root user to expose them.

Let's change the port to another one
~$ podman run -p 8080:80 -d nginx~

Check with
~$ podman ps~

And also
~$ ps aux | grep nginx~
